### ISSUE TITLE
Share insight about theme props

### ISSUE THREAD

**Issue by mittnavnermike** [jameslnewell/styled-components-spacing#21]
Hey, thanks for a great package.

This is not an issue, but I was hoping you could share som insight. I am wondering where `theme` argument is coming from in the example below. I haven't been able to find out where the `theme` is passed into the functions without the `_` prefix. I am trying to grab the theme values for all my own mixins, but I haven't yet managed.

```js
export function p(values: Values) {
  return function({ theme }: { theme: Theme }) {
    return _p(values, theme);
  };
}
```

**Comment by mittnavnermike** [comment]
I've been testing a bit more and managed to get the `theme`. Still not sure how it works, but I'm guessing this is some inner workings of `styled-components` that returns the props and theme automagically?

**Comment by lauriejones** [comment]
Hey Mike, yes you're right. Styled Components is doing some magic there. From the docs:

> styled-components has full theming support by exporting a <ThemeProvider> wrapper component. This component provides a theme to all React components underneath itself via the context API. In the render tree all styled-components will have access to the provided theme, even when they are multiple levels deep.
>
> [Docs ref](https://styled-components.com/docs/advanced#theming)


And if these spacing utilities are being used outside of a `ThemeProvider`, or inside one with no custom breakpoints/spacing sizes defined, then the [default values are used](https://github.com/jameslnewell/styled-components-spacing/blob/master/src/core.js#L33).

Hope that helps!

**Comment by mittnavnermike** [comment]
Great, thanks for this :)
