### ISSUE TITLE
Applying spacing to child element instead of wrapping in another div

### ISSUE THREAD

**Issue by alexcroox** [jameslnewell/styled-components-spacing#7]
Is there a possibility of utilising `Children` and `cloneElement` to apply the padding/margin to the element you are wrapping, rather than creating a div around it?

```
 const child = Children.only(children)
 return cloneElement(child, {
```

**Comment by jameslnewell** [comment]
To do that you'd need to generate a class name using `styled-components` and pass it down to the cloned element. I don't think `styled-components` has an API for this. I think there has previously been some discussion on it and it was decided that it wasn't the direction they wanted to head (the issue name didn't have the best keywords so I can't find it now)

Here's some other ways you can apply the margin/padding to the child element:

On a component written in `styled-components`:
```js
import styled from 'styled-components';
import {my, p} from 'styled-components-spacing';

const MyComponent = styled`
  ${my(4)}
  ${p(2)}
  ...your other styles...
`;
```

On a component not written in `styled-components`:
```js
import styled from 'styled-components';
import {my, p} from 'styled-components-spacing';
import OtherComponent from 'other-library';

const MyComponent = styled(OtherComponent)`
  ${my(4)}
  ${p(2)}
`;
```
> Note: OtherComponent must accept the `className` prop

**Comment by alexcroox** [comment]
OK that's a shame no worries. I tried this lib and immediately ran into issues with having an extra div wrapper. For example wanting to add margin-right to the 1 of 2 inline-block buttons
